config/routes.rb
Rails.application.routes.draw do
  resources :markers
  resources :categories
  resources :types
  get 'api_json', to: 'categories#api_json'
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/marker.rb
class Marker < ApplicationRecord
  
  has_and_belongs_to_many :categories, dependent: :nullify

 

  def name_category
    Category.references(:marker).where(id: category_id).pluck :name
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: %i[ show edit update destroy ]

  # GET /markers or /markers.json
  def index
    @markers = Marker.all
    @marker = Marker.new
    @markers = Marker.all.order(name: :desc)
    #@categories = Category.all.map{ |category| [category.name, category.id]}

  end

  # GET /markers/1 or /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
    #@categories = Category.all.map{|category| [category.name, category.id]}
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers or /markers.json
  def create
    @marker = Marker.new(marker_params)
    unless @marker.save
      render json: @marker.errors, status: :unprocessable_entity
    end
    # respond_to do |format|
    #   if @marker.save
    #     format.html { redirect_to @marker, notice: "Marker was successfully created." }
    #     format.json { render :show, status: :created, location: @marker }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @marker.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /markers/1 or /markers/1.json
  def update
    @marker.update(marker_params)
    # respond_to do |format|
    #   if @marker.update(marker_params)
    #     format.html { redirect_to @marker, notice: "Marker was successfully updated." }
    #     format.json { render :show, status: :ok, location: @marker }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @marker.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /markers/1 or /markers/1.json
  def destroy
    @marker.destroy
    # respond_to do |format|
    #   format.html { redirect_to markers_url, notice: "Marker was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marker_params
      params.require(:marker).permit(:category_id, :name, :url, {category_ids: []})
    end
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_form.html.erb
<div class="container"><hr>
  <%= link_to 'All Categories', categories_path %> |
 <hr>
  <%= form_with(model: marker, remote: true, data: { confirm: 'Desea continuar?'}) do |form| %>
    <% if marker.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(marker.errors.count, "error") %> prohibited this marker from being saved:</h2>

        <ul>
        <% marker.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :categories %><br>
      <%= form.collection_check_boxes(:category_ids, Category.all,
        :id, :name) do |b| %> 
          <%= b.label class:"label-checkbox" do%>
          <%=b.check_box + b.text%> 
        <%end%>
      <% end %> 
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :url %>
      <%= form.text_field :url %>
    </div>

    <div class="actions">
      <%= form.submit data: {disable_with: 'Creando'} %>
    </div><hr>
  <% end %>
</div>

app/views/markers/_marker.html.erb
<div class="container">
  <p id="<%= marker.id%>">
    <strong><%= marker.name %></strong>
    <p><%= marker.name_category[0] %></p>
    <p><a href=<%= marker.url %> target="_blanck"><%= marker.url %></a></p>
    <%= link_to 'Show', marker, remote: true , class: "btn btn-light" %>
    <%= link_to 'Edit', edit_marker_path(marker), remote: true,class: "btn btn-light" %>
    <%= link_to 'Destroy', marker, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light" %></td><hr>
  </p>
</div>

app/views/markers/create.js.erb
$("#all-markers").append(`<%= escape_javascript render @marker%>`)

app/views/markers/destroy.js.erb
$(`#<%=@marker.id%>`).remove()

app/views/markers/edit.html.erb
<h1>Editing Marker</h1>

<%= render 'form', marker: @marker %>

<%= link_to 'Show', @marker %> |
<%= link_to 'Back', markers_path %>

app/views/markers/edit.js.erb
$(`#<%=@marker.id%>`).html(`<%= j render 'form', marker: @marker %>`)

app/views/markers/index.html.erb
<div class="container">  
  <p id="notice"><%= notice %></p>

  <h1>Markers</h1>
  <%= render 'form', marker: @marker%>

  <ul id="all-markers">
    <%= render @markers%>
  </ul>

  <br>

  
</div>  

app/views/markers/new.html.erb
<div class="container">
    <h1>New Marker</h1>

    <%= render 'form', marker: @marker %>

    <%= link_to 'Back', markers_path %>
</div>

app/views/markers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @marker.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @marker.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @marker.url %>
</p>

<%= link_to 'Edit', edit_marker_path(@marker) %> |
<%= link_to 'Back', markers_path %>

app/views/markers/show.js.erb
alert(`<%= @marker.name%>`)

app/views/markers/update.js.erb
$(`#<%=@marker.id%>`).html(`<%= j render @marker %>`)