config/routes.rb
Rails.application.routes.draw do
  resources :markers
  resources :categories
  resources :types
  get 'api_json', to: 'categories#api_json'
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent_category, class_name: "Category", optional: true, foreign_key: 'category_id'
  has_many :children_categories, class_name: "Category", dependent: :destroy
  
  belongs_to :type
  has_many :markers, dependent: :destroy
  

  

  def self.all_the_child_categories
    children_categories = []
    self.children_categories.each do |child_category|
        children_categories << child_category.name
    end
    children_categories
  end

  def self.parent_category
    where(category_id: nil) #que muestra todos los padres porque que no tienen padre asignado
  end

  def name_type
    Type.references(:category).where(id: type_id).pluck :name
  end

  def public_options
    if public == true
        'Privado'
    else
        'Publico'
    end
  end
  # def name_parent(id)
  #   if id
  #     Category.find_by(id: id).name
  #   else
  #     ""
  #   end
  # end

  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :set_categories, only: [:index, :edit, :new]
  # before_action :set_types, only: [:index, :new, :edit]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @category = Category.new
    @categories_ids = Category.all.map{ |category| [category.name, category.id]}
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    
  end

  # POST /categories or /categories.json
  def create
    sleep 1
    @category = Category.new(category_params)
    unless @category.save
      render json: @category.errors, status: :unprocessable_entity
    end
    # respond_to do |format|
    #   if @category.save
    #     format.html { redirect_to @category, notice: "Category was successfully created." }
    #     format.json { render :show, status: :created, location: @category }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @category.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def api_json
    @markers = Marker.all
    @category_api = Category.where(public: false)
    hash_final = {}
    marker_array = []
    category_array = []

    @markers.each do |m|
      obj_marker = {
        name: m.name,
        url: m.url,
        category_id: m.category_id
      } 
      marker_array.push(obj_marker)
    end
    
    hash_final[:Markers] = marker_array

    @category_api.each do |c|
      obj_cat = {
        name: c.name,
        public: c.public, 
        category_id: c.category_id,
        type_id: c.type_id
      } 
      category_array.push(obj_cat)
    end
    hash_final[:Categories] = category_array
    render json: hash_final
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @category.update(category_params)
    # respond_to do |format|
    #   if @category.update(category_params)
    #     format.html { redirect_to @category, notice: "Category was successfully updated." }
    #     format.json { render :show, status: :ok, location: @category }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @category.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def set_categories
      @categories_ids = Category.all.map{ |category| [category.name, category.id]}
    end

    # def set_types
    #   @types = Type.all.map{ |type| [type.name, type.id]}
    # end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_id, :type_id, :name, :public)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="container">  
  <p id="<%= category.id%>">
    <p><strong><%= category.name %></strong>
      <% if category.parent_category 
         category.parent_category
        else
          'No tiene categoria padre'
        end 
      %>
    </p>
      <p>
      <%= link_to 'Show', category, remote: true, class: "btn btn-light" %>
      <%= link_to 'Edit', edit_category_path(category), remote: true, class: "btn btn-light" %>
      <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light"  %>
      </p><hr>
  </p>
</div>

app/views/categories/_form.html.erb
<div class="container"><hr>
  
  <%= link_to 'Markers', markers_path %> |
  <%= link_to 'Types', types_path %> |
  <%= link_to 'Api Json', api_json_path %> |
  <%= link_to 'Dashboard', root_path %><hr>

  <%= form_with(model: category, remote: true, data: { confirm: '¿Desea confirmar?'}) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :type_id %>
      <%= form.collection_select :type_id , Type.all, :id, :name, prompt: true  %>
    </div>

    <div class="field">
      <%= form.label :public %>
      <%= form.select :public,[false,true] %>
    </div>

    <div class="actions">
      <%= form.submit data: {disable_with: "Creando"} %>
    </div><hr>
  <% end %>
</div>

app/views/categories/create.js.erb
$("#all-categories").append(`<%= escape_javascript render @category%>`)

app/views/categories/destroy.js.erb
$(`#<%=@category.id%>`).remove()

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/edit.js.erb
$(`#<%=@category.id%>`).html(`<%= j render 'form', category: @category %>`)

app/views/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h2>Category</h2>
  <%= render 'form', category: @category %>

  <ul id="all-categories">
    <%= render @categories%>
  </ul>
  <br>

  
</div>

app/views/categories/new.html.erb
<div class="container">    
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<p>
  <strong>Type:</strong>
  <%= @category.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Public:</strong>
  <%= @category.public %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/show.js.erb
alert(`<%= @category.name%>`)

app/views/categories/update.js.erb
$(`#<%=@category.id%>`).html(`<%= j render @category %>`)